### ISSUE TITLE
ADDED BENGALI README FILE FOR BENGALI AUDIENCE

### ISSUE THREAD

**Issue by alamin-karno** [imaaquibali/awesome-github-profile-readme#41]
### Please describe your issue.

There is no option to read the repository 'README.md' file in Bengali.

### Describe the solution you'd like

I have added a new 'README.md' with a Bengali translation. This is for the people who want to learn in their native languages.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by imaaquibali** [comment]
@alamin-karno Nice work man :)
