### ISSUE TITLE
Add my profile's README.md

### ISSUE THREAD

**Issue by Jagadesh-Ronanki** [imaaquibali/awesome-github-profile-readme#43]
Hi imaaquibali,
I want to add my readme into this awesome project.

Regards,
R. Jagadesh

**Comment by imaaquibali** [comment]
@Jagadesh-Ronanki Go for it :)

**Comment by Ishukumarpathak** [comment]
I also want to work on that. Please assign me the same.

**Comment by Jagadesh-Ronanki** [comment]
You can raise a new issue @Ishukumarpathak 👍 all the best
